import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outCerts = path.join(__dirname, 'src', 'data', 'certs');
const outProjs = path.join(__dirname, 'src', 'data', 'projects');

fs.mkdirSync(outCerts, { recursive: true });
fs.mkdirSync(outProjs, { recursive: true });

function makeGenericOptions(correctText, wrong1, wrong2, wrong3) {
  return [
    { text: correctText, feedback: "Correct!" },
    { text: wrong1, feedback: "Incorrect approach." },
    { text: wrong2, feedback: "Incorrect approach." },
    { text: wrong3, feedback: "Incorrect approach." }
  ];
}

function makeCert(id, simId, title, qData) {
  return {
    "simulation_id": simId,
    "certification_title": title,
    "scenarios": [
      {
        "scenario_id": "SC01",
        "title": "Comprehensive Mastery",
        "questions": qData.map((q, idx) => ({
          "q_id": `Q${idx+1}`,
          "q": q.text,
          "explain_this": q.explain || "Applying standard HR principles.",
          "options": makeGenericOptions(q.ans, ...q.wrong),
          "correct_index": 0
        }))
      }
    ]
  };
}

function makeProjStep(text, ans, ...wrong) {
  return {
    "step_type": "mcq",
    "q": text,
    "options": [ {text: ans}, ...wrong.map(w => ({text: w})) ],
    "validation": { "type": "single_choice_index", "correct_index": 0 }
  };
}

function makeProj(id, title, stepsData) {
  return {
    "simulation_id": id,
    "project_title": title,
    "tools_pair": ["HRIS", "Core Tools"],
    "technical_skills": [
      { "skill_id": "TS1", "name": "Project Execution", "artefact_label": "Project Master Plan", "artefact_type": "doc" }
    ],
    "steps": stepsData.map((s, idx) => {
       const step = makeProjStep(s.text, s.ans, ...s.wrong);
       step.step_id = `S${idx+1}`;
       return step;
    })
  };
}

// === REAL QUESTIONS FOR CERTS ===

const cert1qs = [
  { text: "A key engineering team experienced a 30% attrition spike last quarter. What is the most effective first step to diagnose the cause?", ans: "Analyze exit interview data alongside recent organizational or leadership changes.", wrong: ["Immediately increase salaries for the entire department by 10%.", "Assume they are leaving for higher pay and do nothing.", "Fire the engineering managers without investigation."], explain: "Data-driven diagnosis comes before immediate costly action." },
  { text: "When implementing a major restructuring, what is the critical HR role in mitigating legal risks?", ans: "Ensuring all termination decisions are documented and follow objectively applied criteria to prevent bias claims.", wrong: ["Leaving managers to decide whom to cut based on 'gut feeling'.", "Delaying the restructuring indefinitely to avoid conflict.", "Telling employees it is their own fault to minimize backlash."], explain: "Objective criteria and documentation protect against wrongful termination claims." },
  { text: "Your company is rapidly expanding from a single office to a remote-first, multi-state workforce. What is the priority enterprise strategy?", ans: "Aligning payroll, taxation, and labor policy compliance across all operating jurisdictions.", wrong: ["Sending standard office equipment to everyone.", "Focusing only on organizing weekly virtual social hours.", "Applying the headquarters state's labor laws to all employees uniformly."], explain: "Compliance complexity scales violently with multi-state operations." },
  { text: "A mid-level manager complains they cannot retain strong talent because the corporate compensation bands are too low. What data should HR provide?", ans: "Recent market salary benchmarking data showing how current bands compare to industry averages.", wrong: ["The salaries of all top executives to show the company makes money.", "The resumes of the departing employees.", "A motivational poster about working for passion, not money."], explain: "Benchmarking standardizes the compensation discussion." },
  { text: "Leadership wants to reduce overall headcount costs by 15% without conducting layoffs. What is the most strategic approach?", ans: "Implement a targeted hiring freeze while restricting contractor budgets and managing voluntary attrition.", wrong: ["Cutting everyone's base salary by 15%.", "Eliminating all employee health benefits.", "Demoting 15% of the workforce arbitrarily."], explain: "A hiring freeze leverages natural attrition to reduce headcount." },
  { text: "When conducting succession planning for a critical C-suite role, what is the best methodology?", ans: "Identifying highly capable internal delegates and mapping their 12-to-18-month developmental gap.", wrong: ["Just assuming the next most senior person will naturally take the job.", "Hiring an external candidate blindly without looking inside.", "Waiting until the executive actually quits to start thinking about it."], explain: "Succession planning requires deliberate gap mapping." },
  { text: "The CEO wants a daily snapshot of 'culture health'. Which leading indicator is easiest to pull and track frequently?", ans: "Tracking the engagement rate on core internal communications and recent pulse survey participation.", wrong: ["Calculating the exact ROI of the last company retreat.", "Detailed psychological profiles of the entire leadership team.", "Reading everyone's private Slack messages."], explain: "Leading indicators of culture include engagement and participation metrics." },
  { text: "During a unionization attempt at a manufacturing site, what must HR instruct line managers to absolutely avoid doing?", ans: "Threatening employees, interrogating them about union ties, or promising benefits to vote 'no'.", wrong: ["Explaining the terms of the current employment contract.", "Listening carefully to employee concerns without making promises.", "Holding legally compliant 'town hall' meetings on company time."], explain: "TIPS (Threaten, Interrogate, Promise, Spy) are illegal labor practices." },
  { text: "A competitor just poached three of your senior sales directors by offering higher sign-on bonuses. Your immediate retention tactic is:", ans: "Conducting stay interviews with the remaining top-tier sales talent to preempt further exits.", wrong: ["Sending angry legal cease and desist letters to the competitor.", "Counteroffering the three departed directors with double the salary.", "Ignoring the situation and assuming no one else will leave."], explain: "Stay interviews stabilize the remaining high-value talent." },
  { text: "When creating an enterprise-grade diversity and inclusion strategy, the most critical foundation is:", ans: "Auditing existing hiring pipelines, promotion rates, and pay equity data to establish a factual baseline.", wrong: ["Just changing the company logo colors for a month.", "Mandating that managers hire specific demographics regardless of qualifications.", "Sending a single company-wide email denouncing bias."], explain: "Real D&I strategy is built on auditable metric baselines." }
];

const cert2qs = [
  { text: "An employee reports that their direct supervisor repeatedly makes inappropriate comments about their appearance. What is your first action?", ans: "Privately interview the reporting employee to gather specific incidents, dates, and potential witnesses.", wrong: ["Confront the supervisor immediately in an open office area.", "Tell the employee to confront the supervisor themselves first.", "Transfer the employee to a different department without asking them."], explain: "Fact-finding begins with a detailed, private intake." },
  { text: "The supervisor admits to the comments but claims they were 'just compliments'. How should HR adjudicate this?", ans: "Explain that company harassment policy focuses on the impact on the recipient, not the intent of the speaker.", wrong: ["Agree that since it was meant nicely, no rule was broken.", "Fire the supervisor on the spot.", "Tell the complaining employee to accept the compliments."], explain: "Intent vs. Impact is the core doctrine of harassment resolution." },
  { text: "During an investigation, a witness asks for absolute anonymity before they will share what they saw. What do you tell them?", ans: "You will maintain strict confidentiality on a need-to-know basis, but cannot guarantee absolute, unconditional anonymity.", wrong: ["Promise absolute anonymity under all circumstances.", "Refuse to speak to them unless they sign a sworn public affidavit.", "Tell them you will share their name with everyone involved."], explain: "Absolute anonymity cannot be legally guaranteed during investigations." },
  { text: "Two employees on the same team are continually arguing over project territory, disrupting the team. What is the best dispute resolution tactic?", ans: "Facilitate a structured mediation session focused on defining clear roles and boundaries moving forward.", wrong: ["Terminate the one who argues loudest.", "Send out a generic team email about 'getting along'.", "Ignore it as 'creative tension'."], explain: "Mediation focuses on boundaries and behavioral agreements." },
  { text: "A high-performing but abrasive salesperson is reported for yelling at an administrative assistant. How do you handle it?", ans: "Address the behavior immediately through the formal disciplinary process; high performance does not excuse policy violations.", wrong: ["Ignore the complaint because the salesperson brings in the most revenue.", "Tell the assistant to avoid the salesperson.", "Give the salesperson a bonus but silently ask them to stop."], explain: "Policy enforcement must be consistent regardless of revenue generation." },
  { text: "An employee on a Performance Improvement Plan (PIP) files a sudden grievance claiming their manager is biased against them. What is the standard protocol?", ans: "Investigate the bias claim separately through HR while keeping the objective execution of the PIP timeline intact.", wrong: ["Immediately cancel the PIP and clear their record.", "Ignore the grievance completely because they are just trying to save their job.", "Fire the manager for causing friction."], explain: "Grievances during a PIP must be investigated, but objective PIP facts stand." },
  { text: "A worker complains about an unsafe condition on the factory floor. The plant manager says fixing it is too expensive. HR's role is:", ans: "Escalate the issue to compliance/legal immediately, as unresolved safety issues create severe liability and regulatory risk.", wrong: ["Agree with the manager to save the budget.", "Tell the worker to be careful.", "Hide the written complaint."], explain: "Safety and OSHA compliance override departmental budgets." },
  { text: "While investigating workplace theft, what is an unacceptable evidence-gathering method?", ans: "Searching an employee's personal vehicle parked in a public lot without their permission or law enforcement present.", wrong: ["Reviewing company-owned security camera footage.", "Auditing company-issued laptops or network access logs.", "Interviewing coworkers who reported suspicious behavior."], explain: "Personal property searches without explicit legal authority violate boundaries." },
  { text: "After completing a harassment investigation that resulted in disciplinary action for the offender, what is the crucial final step?", ans: "Following up with the original reporter to ensure the behavior has stopped and no retaliation has occurred.", wrong: ["Posting the investigation results on the intranet.", "Never speaking to the reporter again to avoid awkwardness.", "Promoting the offender to a new department."], explain: "Monitoring for retaliation is a legal and ethical requirement." },
  { text: "When drafting an official warning letter, the tone and content should be:", ans: "Factual, objective, detailing the specific policy breached, and outlining the expected behavioral correction.", wrong: ["Highly emotional and judgmental of the employee's character.", "Vague, avoiding specific details so it can't be challenged.", "Apologetic, blaming the strict company rules for the warning."], explain: "Documentation must be objective and legally defensible." }
];

const cert3qs = [
  { text: "A manager wants to give their team member a poor performance rating, but there is no documented feedback or coaching prior to the annual review. What is the issue?", ans: "The 'surprise' review violates the principle of continuous feedback and exposes the company to unfair dismissal claims.", wrong: ["The rating isn't poor enough.", "The employee will still get their full bonus.", "There is no issue; managers can rate however they please."], explain: "Performance ratings require an audit trail of continuous feedback." },
  { text: "What is the primary psychological benefit of implementing quarterly check-ins rather than a single annual appraisal?", ans: "It reduces recency bias and allows for course correction while goals are still relevant.", wrong: ["It allows the company to fire people faster.", "It forces managers to do more paperwork.", "It guarantees everyone will get a raise four times a year."], explain: "Frequent check-ins defeat recency bias." },
  { text: "An employee's self-appraisal claims they 'exceeded all expectations', but their manager rated them as 'meets expectations'. How should this be resolved?", ans: "The manager should hold a calibration meeting with the employee to align their understanding of the rubric and objective deliverables.", wrong: ["HR should automatically average the two ratings.", "The manager should tell them they are delusional.", "The employee should be fired for lying on the form."], explain: "Discrepancies require calibration against objective rubrics." },
  { text: "When writing SMART goals, what does the 'M' stand for, and why is it critical?", ans: "Measurable; because if a goal lacks clear metrics, successful completion is purely subjective.", wrong: ["Mandatory; because all goals must be forced by HR.", "Magical; because the goal should be impossible to reach.", "Managerial; because only managers can set them."], explain: "Measurable goals remove subjectivity during reviews." },
  { text: "In a '360-degree feedback' system, input is gathered from:", ans: "The employee's manager, peers, direct reports, and sometimes clients or stakeholders.", wrong: ["Only the CEO and the Board of Directors.", "The employee themselves, 360 times.", "A random selection of competing companies."], explain: "360 feedback pulls from all tactical interactions around the employee." },
  { text: "A common cognitive bias in performance reviews where a manager rates an employee highly in all areas simply because they excel in one specific area is called:", ans: "The Halo Effect.", wrong: ["The Horns Effect.", "Recency Bias.", "Confirmation Bias."], explain: "The Halo effect occurs when one positive trait overshadows everything else." },
  { text: "To protect the integrity of a Performance Improvement Plan (PIP), what must the document explicitly contain?", ans: "A clear timeline, objectively measurable improvement goals, and the consequences of failing to meet them (e.g., termination).", wrong: ["A promise of a promotion at the end.", "Vague statements like 'do better at your job'.", "A signature from every member of the department."], explain: "PIPs must be legally robust, objective, and clear on consequences." },
  { text: "During a calibration session, multiple managers discuss their team ratings to ensure fairness across the department. What is the primary goal of this meeting?", ans: "To eliminate individual manager leniency or strictness bias so 'exceeds expectations' means the same thing everywhere.", wrong: ["To force everyone into a strict 10% bottom-tier quota.", "To gossip about low performers.", "To inflate all ratings so the department looks good to the CEO."], explain: "Calibration ensures cross-departmental rating equity." },
  { text: "If an employee demonstrates excellent technical skills but toxic behavior that undermines team morale, how should their performance review reflect this?", ans: "The review must penalize the behavioral failure, usually through a 'values' or 'competency' rating that impacts their total score.", wrong: ["Ignore the behavior because technical skills are all that matters.", "Give them a perfect score but secretly dislike them.", "Promote them so they bother a different team."], explain: "Performance is both 'what' is achieved and 'how' it is achieved." },
  { text: "When giving constructive feedback, the SBI model is highly effective. What does SBI stand for?", ans: "Situation, Behavior, Impact.", wrong: ["Stop, Breathe, Interrogate.", "Standardize, Base, Inform.", "Salary, Bonus, Incentives."], explain: "The SBI model anchors feedback in reality." }
];

const cert4qs = [
  { text: "In India, an establishment with 20 or more employees is mandatorily covered under which key statutory act for retirement benefits?", ans: "The Employees' Provident Funds and Miscellaneous Provisions Act, 1952.", wrong: ["The Minimum Wages Act.", "The Payment of Bonus Act.", "The Factories Act."], explain: "EPF compliance is triggered at 20 employees." },
  { text: "Under the POSH (Prevention of Sexual Harassment) Act, what is the mandatory internal body a company with over 10 employees must constitute?", ans: "The Internal Complaints Committee (ICC).", wrong: ["The HR Regulatory Board.", "The Local Police Liaison Team.", "The Corporate Ethics Panel."], explain: "The ICC is a strict legal mandate under POSH." },
  { text: "During a surprise labor inspection, the inspector demands to see the 'Muster Roll'. What are they asking for?", ans: "The official attendance register of the employees in the establishment.", wrong: ["The payroll bank transfer receipts.", "The employee training certificates.", "The company's articles of incorporation."], explain: "The Muster Roll is the statutory attendance record." },
  { text: "When an employee resigns and serves out their notice period, by when must their Full & Final (F&F) settlement ideally be processed according to best practices/standard labor guidelines?", ans: "Within a few days of their last working day, typically by the next payment cycle at the latest to avoid distress and disputes.", wrong: ["After 6 months.", "Whenever the finance team feels like it.", "Never, if they were a bad performer."], explain: "Prompt F&F settlements prevent labor court escalations." },
  { text: "What is an NDA in the context of employee onboarding?", ans: "Non-Disclosure Agreement: a contract binding the employee to keep company IP and trade secrets confidential.", wrong: ["National Dependent Allowance.", "New Directives Assessment.", "Non-Disciplinary Action plan."], explain: "NDAs protect corporate intellectual property." },
  { text: "A background verification (BGV) report returns a 'red flag' stating the candidate fabricated their previous degree. What is the standard compliance process?", ans: "Issue a show-cause notice based on the BGV report, and if unresolvable, terminate employment for material misrepresentation.", wrong: ["Ignore it if they are doing a good job.", "Call their previous university and scream at the registrar.", "Deduct their salary by 50%."], explain: "Material misrepresentation on an application is grounds for immediate termination." },
  { text: "Gratuity in India is payable to an employee who terminates their employment after rendering continuous service for not less than:", ans: "Five years.", wrong: ["One year.", "Two years.", "Ten years."], explain: "Gratuity eligibility unlocks after 5 years of continuous service." },
  { text: "To maintain GDPR or basic data privacy compliance in HR Operations, you must ensure that:", "ans": "Employee personal and medical data is encrypted, stored securely, and accessed strictly on a need-to-know basis.", "wrong": ["All employee data is posted on the company's public website.", "Any manager can view anyone's medical history.", "Resumes are printed and left on open desks."], "explain": "Data privacy requires secure storage and restricted access." },
  { text: "If an employee requests statutory maternity leave under the Maternity Benefit Act, how many weeks of paid leave are they entitled to for their first child?", ans: "26 weeks.", wrong: ["12 weeks.", "6 weeks.", "52 weeks."], explain: "The Maternity Benefit Act grants 26 weeks for the first two children." },
  { text: "What defines an 'independent contractor' versus a full-time 'employee' in the eyes of compliance audits?", ans: "Contractors control how and when they perform the work and use their own equipment; employees are directed dynamically by the company.", wrong: ["Employees get paid less than contractors.", "Contractors only work on Tuesdays.", "There is no legal difference between the two."], explain: "Direction, control, and equipment ownership define the employment relationship." }
];

const cert5qs = [
  { text: "Your CEO wants to know how many employees left the company voluntarily last year as a percentage of the total workforce. Which metric provides this?", ans: "The Voluntary Attrition Rate.", wrong: ["The Offer Acceptance Rate.", "The Time-to-Fill metric.", "The Compa-Ratio."], explain: "Voluntary Attrition tracks self-initiated exits against average headcount." },
  { text: "If a candidate is offered a salary of $90,000, and the midpoint of the salary band for that role is $100,000, what is the candidate's Compa-Ratio?", ans: "0.90 (or 90%).", wrong: ["1.10 (or 110%).", "0.10 (or 10%).", "90,000%"], explain: "Compa-ratio = Actual Salary / Midpoint. 90k/100k = 0.9." },
  { text: "To measure the effectiveness and speed of your Talent Acquisition team, what combination of metrics is most critically analyzed together?", ans: "Time-to-Fill and Cost-per-Hire.", wrong: ["eNPS and Sick Leave Days.", "Revenue-per-Employee and Training Hours.", "Retirement Rate and Dress Code Violations."], explain: "Speed (Time-to-Fill) and Efficiency (Cost-per-Hire) define recruiting ROI." },
  { text: "The eNPS (Employee Net Promoter Score) is calculated by asking employees a single prominent question. What is it?", ans: "'On a scale of 0-10, how likely are you to recommend this company as a place to work?'", wrong: ["'Do you like your boss?'", "'How much do you want to be paid?'", "'What is your favorite cafeteria meal?'"], explain: "eNPS mirrors consumer NPS, tracking referral likelihood." },
  { text: "When building a predictive attrition model, which 'leading indicator' data point is historically highly correlated with an employee quitting?", ans: "A sudden drop in the employee's usage of internal collaboration tools (like Slack/Teams) or skipped 1-on-1s.", wrong: ["The day of the week they were hired.", "Their favorite programming language.", "The make of their personal vehicle."], explain: "Withdrawal behavior in comms tools often precedes a formal resignation." },
  { text: "You notice that the 'Quality of Hire' metric is dropping. How is this metric typically calculated?", ans: "By averaging the new hire's performance review scores, ramp-up time, and retention rate over their first year.", wrong: ["By counting how many questions they answered right in the interview.", "By checking the spelling on their resume.", "By how many hours they work in their first week."], explain: "Quality of Hire bridges recruiting and actual on-the-job performance." },
  { text: "A department has an exceptionally high 'Absence Rate' (Abseentism). What is the standard formula to calculate this?", ans: "(Total Unplanned Absent Days / Total Available Work Days in the period) x 100.", wrong: ["(Approved Vacations / Total Employees).", "Days worked minus weekends.", "Total sick days divided by CEO salary."], explain: "Absence Rate tracks unplanned productivity loss." },
  { text: "Revenue Per Employee is a classic HR metric used to demonstrate productivity. How is it calculated?", ans: "Total Company Revenue divided by Total Number of FTEs (Full-Time Equivalents).", wrong: ["Total HR Budget divided by Total Revenue.", "Employee Salary divided by Company Profit.", "Total Sales divided by the number of salespeople only."], explain: "Revenue per FTE tracks the broader macro-efficiency of the workforce." },
  { text: "If you want to track whether your company is successfully promoting diversity in leadership, which metric is most revealing?", ans: "The Promotion Rate mapped explicitly by demographic groups (e.g., gender, ethnicity) compared to the baseline population.", wrong: ["The total number of diversity training seminars held.", "The overall headcount of the company.", "The number of hours HR spends on LinkedIn."], explain: "Demographic promotion rates reveal pipeline and systemic blockers." },
  { text: "When presenting HR data to the executive board, what is the best practice for data visualization?", ans: "Using clean, annotated dashboards that highlight actionable trends rather than just dumping raw spreadsheets.", wrong: ["Providing a 100-page unformatted Excel printout.", "Using 3D pie charts with 25 different undocumented colors.", "Avoiding numbers entirely and just telling stories."], explain: "Executives need insights (trends and actions), not raw queries." }
];

// === REAL QUESTIONS FOR PROJECTS === //

const proj1qs = [
  { text: "Step 1: An employee submits a formal grievance about unfair shift allocations via email. What is the immediate first action?", ans: "Acknowledge receipt in writing and clarify the timeline for the investigation.", wrong: ["Forward the email directly to the accused manager.", "Delete the email, assuming it will blow over.", "Call the police immediately."] },
  { text: "Step 2: You review the grievance. To ensure a fair investigation, who should lead the fact-finding?", ans: "An impartial HR investigator who has no direct reporting lines to anyone involved in the case.", wrong: ["The accused manager's best friend in the company.", "The complaining employee's direct peer.", "The CEO, to save time."] },
  { text: "Step 3: You schedule the intake interview with the complainant. How should you format your questions?", ans: "Prepare open-ended, non-leading questions focusing on objective facts (dates, times, specific statements).", wrong: ["Prepare questions that tell them they are probably misinterpreting things.", "Write leading questions that already assume the manager is guilty.", "Don't prepare questions; wing it."] },
  { text: "Step 4: The complainant provides a list of witnesses. What must you explicitly instruct the complainant at the end of the meeting?", ans: "To maintain strict confidentiality and not discuss the investigation with coworkers to avoid compromising witness testimony.", wrong: ["To post about it on LinkedIn so people know what's happening.", "To confront the witnesses directly to prep them.", "To apologize to the manager."] },
  { text: "Step 5: When interviewing the accused manager, they become defensive and angry. What is your response strategy?", ans: "Remain calm, neutrally restate the purpose of the fact-finding, and allow them to review the specific allegations.", wrong: ["Yell back to establish authority.", "End the meeting and immediately terminate them.", "Agree with them that the employee is probably lying."] },
  { text: "Step 6: You collect shift allocation logs for the past three months. What are you looking for?", ans: "Objective data patterns that either corroborate or contradict the employee's claim of unfair allocation.", wrong: ["The manager's personal bank statements.", "The employee's browser history.", "Nothing, data just looks good in the file."] },
  { text: "Step 7: You must draft the investigation findings. The document should be structured to separate:", ans: "Factual evidence from conclusions, avoiding emotional language.", wrong: ["Gossip from salary data.", "Good employees from bad ones based on your gut.", "Legal threats from personal opinions."] },
  { text: "Step 8: You conclude the manager showed unintentional bias in scheduling. What is the proportionate mitigation step?", ans: "Require the manager to attend bias training and implement a randomized or HR-audited scheduling system.", wrong: ["A 50% pay cut for the manager.", "Fire everyone on the shift.", "Do nothing because it was unintentional."] },
  { text: "Step 9: You meet with the original complainant to close out the process. What do you communicate?", ans: "That the investigation is concluded and corrective actions have been taken to ensure fair scheduling moving forward, without disclosing the exact disciplinary details given to the manager.", wrong: ["The exact details of the manager's punishment.", "That they were right and the manager is an awful person.", "Nothing. Silence is gold."] },
  { text: "Step 10: To prevent future occurrences, what system-level change should you implement?", ans: "Draft an addendum to the scheduling policy requiring multi-level approval or software automation for complex shifts.", wrong: ["Ban all shifts.", "Stop hiring people who complain.", "Install cameras in the breakroom."] }
];

const proj2qs = [
  { text: "Step 1: The hiring manager informs you a new Senior Developer accepts the offer. To start the 30-day plan, what must happen before Day 1?", ans: "Pre-boarding: Provision IT equipment, software access, and send a welcome email outlining Day 1 logistics.", wrong: ["Nothing, wait until they walk in the door.", "Send them a 400-page manual to memorize.", "Tell the team to ignore them until week 3."] },
  { text: "Step 2: Who should you designate to handle the socio-cultural integration of the new hire during their first month?", ans: "An assigned 'Onboarding Buddy' who is a peer, not their direct manager.", wrong: ["The CEO.", "The facilities manager.", "No one, they should figure it out."] },
  { text: "Step 3: On Day 1, what is the most critical objective to accomplish?", ans: "Ensuring they feel welcomed, have a working laptop/access, and understand the high-level company mission.", wrong: ["Having them write complex production code.", "A grueling 8-hour HR policy lecture.", "Leaving them alone at a desk to read the intranet."] },
  { text: "Step 4: For Week 1, the manager should outline expectations. This is best formatted as:", ans: "A structured checklist of 'quick wins', key team members to meet, and basic system orientations.", wrong: ["A vague instruction to 'look around'.", "An immediate performance review.", "A massive project due by Friday."] },
  { text: "Step 5: To ensure the new hire understands the company culture, what event should be scheduled in Week 2?", ans: "Shadowing sessions with adjacent departments to understand cross-functional workflows.", wrong: ["A mandatory trust fall retreat.", "A severe stress test to see if they break.", "A quiz on the names of all board members."] },
  { text: "Step 6: By the end of Week 2, the manager requests an HR check-in. What is the focus of this 15-minute sync?", ans: "Pulsing their engagement, unblocking any access/tooling issues, and ensuring alignment with the manager's instructions.", wrong: ["Interrogating them about their loyalty to the company.", "Giving them their first warning letter.", "Asking them to refer 10 friends immediately."] },
  { text: "Step 7: In Week 3, the new hire should transition into:", ans: "Executing their first low-risk, independent task or project with manager supervision.", wrong: ["Managing the entire department.", "Still just reading manuals.", "Training other brand-new hires."] },
  { text: "Step 8: How do you measure the success of the onboarding plan objectively at the 30-day mark?", ans: "By reviewing the completion rate of the 30-day milestone checklist and capturing an eNPS survey from the new hire.", wrong: ["By how early they arrive to work.", "By checking if they bought company merch.", "By seeing if they have memorized the handbook."] },
  { text: "Step 9: At the official 30-day feedback meeting with the manager, what is the agenda?", ans: "Reviewing the completed quick wins, providing two-way constructive feedback, and setting goals for the next 60 days.", wrong: ["Deciding immediately if they get a raise.", "Firing them if they made one mistake.", "A casual chat about the weather."] },
  { text: "Step 10: To iterate and improve your onboarding template, you should:", ans: "Consolidate the new hire's feedback on bottlenecks they faced and update the IT/Manager checklists accordingly.", wrong: ["Lock the template forever.", "Assume it's perfect.", "Blame the new hire if they found the process confusing."] }
];

const proj3qs = [
  { text: "Step 1: The CEO asks you to update the company's outdated Work-From-Home policy. What is the crucial first step?", ans: "Survey the existing business needs and benchmark competitor policies to define a realistic baseline.", wrong: ["Instantly ban all WFH.", "Copy-paste a policy from a Google search without reading it.", "Send out an email saying WFH is now unlimited with no rules."] },
  { text: "Step 2: You need to define the 'Scope' of the policy. Which statement is correct?", ans: "The scope must explicitly state which roles, locations, or job formats are eligible versus ineligible for WFH.", wrong: ["The scope should just say 'everyone'.", "The scope should be kept a secret.", "The scope only applies to the executive team."] },
  { text: "Step 3: A manager asks how they will monitor productivity if people are at home. You draft a clause that states:", ans: "Productivity will be measured by output, KPIs, and deliverables, rather than screen-time or hours logged.", wrong: ["Managers must install keystroke trackers on all laptops.", "Employees must keep their webcams on for 8 hours a day.", "Productivity cannot be monitored at home."] },
  { text: "Step 4: You must address 'Information Security' in the WFH policy. What is the required mandate?", ans: "Employees must use company-issued VPNs on secured networks and avoid working on confidential data in public spaces.", wrong: ["Employees can use personal laptops for everything.", "Security doesn't matter at home.", "Employees must buy their own enterprise firewalls."] },
  { text: "Step 5: To handle exceptions (e.g., someone needing to WFH 5 days a week due to illness), the policy must include:", ans: "A clear escalation matrix and process for requesting medical or special accommodations via HR.", wrong: ["A strict 'no exceptions ever' clause.", "A clause saying managers can play favorites.", "A rule that exceptions cost money."] },
  { text: "Step 6: Before finalizing the draft, who must absolutely review the document to mitigate legal risk?", ans: "The corporate legal counsel or compliance officer, to ensure alignment with local labor and tax laws.", wrong: ["The social media team.", "The newest intern.", "No one, HR has final say on all legal matters."] },
  { text: "Step 7: The policy is approved. What is the most effective change-management strategy to roll it out?", ans: "Host a targeted training session for managers on how to enforce it, followed by a company-wide town hall and FAQ release.", wrong: ["Silently upload it to an obscure folder on the intranet.", "Email it at 11:59 PM on a Friday.", "Print it and tape it to the bathroom mirrors."] },
  { text: "Step 8: How do you ensure employees have officially acknowledged the new compliance rules in the policy?", ans: "Deploy it via the HRIS requiring a digital signature/checkbox acknowledgment from every employee.", wrong: ["Assume if they opened the email they read it.", "Ask them in the hallway.", "Make an announcement on a megaphone."] },
  { text: "Step 9: Two weeks after rollout, a department head refuses to let their eligible team WFH. How do you respond?", ans: "Meet with the department head to understand their resistance and firmly align them with the executive-approved policy.", wrong: ["Let them do whatever they want.", "Fire the whole department.", "Revoke the policy for the entire company."] },
  { text: "Step 10: Six months post-rollout, how do you audit the policy's success?", ans: "Analyze productivity metrics, review office-space cost savings, and pulse employee satisfaction via a survey.", wrong: ["Just assume it's fine.", "Count how many people complain to HR daily.", "Check the weather."] }
];

const proj4qs = [
  { text: "Step 1: The engineering director needs a new Data Scientist. What is the very first step of the Hiring Loop?", ans: "Conduct an Intake Meeting to define the must-have skills, salary bounds, and interview panel clearly.", wrong: ["Start messaging random people on LinkedIn.", "Post the job title to a job board with no description.", "Call an agency and tell them to find someone fast."] },
  { text: "Step 2: You review the draft Job Description (JD). It lists 25 'Required Skills'. What is your strategic advice?", ans: "Advise the manager to separate 'Must-Haves' (core competencies) from 'Nice-to-Haves' to avoid filtering out diverse, capable talent.", wrong: ["Add 10 more skills just in case.", "Delete the skills section entirely.", "Keep it; we only want unicorns."] },
  { text: "Step 3: To ensure an unbiased evaluation process during the loop, you must mandate the use of:", ans: "A standardized interview scorecard anchored to specific behavioral traits and technical competencies.", wrong: ["A 'vibe check' by the team.", "A subjective rating out of 10 based on gut feeling.", "Reviewing their social media profiles together."] },
  { text: "Step 4: You begin sourcing. The pipeline is heavily skewed toward one demographic. What is the immediate correction?", ans: "Expand sourcing channels to diverse professional networks and audit the JD language for exclusionary terminology.", wrong: ["Lower the technical bar entirely.", "Ignore it, talent is talent.", "Only interview that demographic to save time."] },
  { text: "Step 5: During the HR phone screen, what are the three critical data points you must capture?", ans: "Salary expectations, notice period/availability, and primary motivation for role alignment.", wrong: ["Their favorite movie, their age, and their marital status.", "Their ability to code, their IQ, and their typing speed.", "Nothing, just talk about the weather."] },
  { text: "Step 6: The candidate progresses to the Technical Interview. How should the technical panel be prepped?", ans: "Assign specific technical domains to specific interviewers to avoid asking the candidate the same coding question three times.", wrong: ["Tell everyone to ask whatever they want.", "Give them no prep; they are senior engineers.", "Tell them to try and make the candidate cry."] },
  { text: "Step 7: The candidate finishes all rounds. It's time for the Debrief. What is the rule of the debrief meeting?", ans: "All interviewers must submit their scorecards BEFORE the meeting to prevent 'Anchoring Bias' from the most senior person.", wrong: ["The most senior person speaks first and tells everyone what to think.", "You calculate an average score and don't discuss it.", "You let the CEO decide blindly."] },
  { text: "Step 8: The panel says 'Hire'. You run references. One reference says the candidate is 'brilliant but hard to work with'. You:", ans: "Probe the reference for specific behavioral examples and contextualize this data with the interview panel's behavioral read.", wrong: ["Immediately reject the candidate.", "Ignore the reference entirely.", "Tell the candidate what their reference said."] },
  { text: "Step 9: You move to Offer Negotiation. The candidate asks for 15% above the approved band. Your tactic is:", ans: "Highlight the total rewards package, understand what drives them (e.g., equity, flexibility), and consult finance for a counter-strategy.", wrong: ["Hang up the phone.", "Immediately say yes without approval.", "Yell at them for being greedy."] },
  { text: "Step 10: The candidate accepts the offer! To cleanly close the Hiring Loop, what is the final administrative action?", ans: "Send professional, constructive rejection updates to other finalists, run background checks, and transition the hire to Onboarding.", wrong: ["Ghost the other candidates.", "Go to sleep.", "Keep interviewing just in case they back out."] }
];

const proj5qs = [
  { text: "Step 1: It's the 1st of the month. You need to pull data for the HR deck. What is the foundational metric of any HR report?", ans: "Current Total Headcount across all departments, split by full-time vs. contingent workers.", wrong: ["The number of birthday cakes bought.", "The total number of job applications received all year.", "The CEO's daily agenda."] },
  { text: "Step 2: You need to calculate the Attrition Rate. You started with 500 headcount, ended with 520, and 15 people resigned. What's the denominator?", ans: "The Average Headcount for the month (510).", wrong: ["The Starting Headcount only.", "The people who resigned.", "The total number of interviews."] },
  { text: "Step 3: What segment of attrition data should you prioritize visualizing for the executive team to show risk?", ans: "Regrettable Attrition—the loss of high-performers or critical-impact roles.", wrong: ["Non-regrettable attrition of poor performers.", "The attrition of summer interns.", "Attrition grouped by alphabetical order of names."] },
  { text: "Step 4: Looking at Talent Acquisition metrics, what does 'Time-to-Fill' actually measure?", ans: "The number of days between an open requisition being approved and the candidate formally accepting the offer.", wrong: ["The time it takes to write a Job Description.", "The duration of the candidate's first interview.", "The time it takes to fire someone."] },
  { text: "Step 5: You notice the Time-to-Fill in Engineering has spiked from 30 days to 65 days. What is your diagnostic action?", ans: "Audit the funnel to see if the bottleneck is top-of-funnel sourcing or delays in manager interview feedback.", wrong: ["Blame the recruiters and move on.", "Assume there are no engineers left in the world.", "Delete the metric from the report to look good."] },
  { text: "Step 6: To report on Diversity, what data point should you include alongside the current demographic breakdown?", ans: "The diversity ratios within the hiring funnel (applicants vs. offers) to highlight pipeline equity.", wrong: ["Just a picture of diverse people.", "The exact home addresses of all employees.", "Only data from 5 years ago."] },
  { text: "Step 7: The CFO wants to see HR's cost-efficiency. Which metric should you add to the 'Financials' section of your report?", ans: "Cost-Per-Hire, breaking down agency fees, job board spend, and internal referral bonuses.", wrong: ["The cost of the office coffee machine.", "The CEO's travel expenses.", "The total revenue of the company's main product."] },
  { text: "Step 8: You import the raw CSV into Tableau/Excel. Design-wise, how should you present the data to the executive board?", ans: "Using highly visual scorecards displaying MoM (Month-over-Month) trends accompanied by a single-sentence insight.", wrong: ["A 40-column spreadsheet in size 8 font.", "A pie chart with 30 different slices.", "No charts, just a wall of text."] },
  { text: "Step 9: You spot a 'Red Flag': 4 employees resigned from the Sales team in one week, all citing identical leadership issues. You must:", ans: "Include this cluster in the Executive Summary with a recommended action plan (e.g., immediate skip-level meetings).", wrong: ["Hide it so the Sales VP doesn't get mad.", "Email the whole company about it.", "Wait for next month to see if it fixes itself."] },
  { text: "Step 10: When presenting the report in the live executive meeting, what is your role as the HR representative?", ans: "To narrate the 'why' behind the numbers, anchoring the data to business outcomes and proposing strategic interventions.", wrong: ["Just read the numbers off the slides monotonously.", "Argue violently if anyone questions the data.", "Hand out the paper and leave the room."] }
];

fs.writeFileSync(path.join(outProjs, 'proj-1.json'), JSON.stringify(makeProj('proj-1', 'Resolve an Employee Grievance Case', proj1qs), null, 2));
fs.writeFileSync(path.join(outProjs, 'proj-2.json'), JSON.stringify(makeProj('proj-2', 'Design a 30-Day Onboarding Plan for a New Hire', proj2qs), null, 2));
fs.writeFileSync(path.join(outProjs, 'proj-3.json'), JSON.stringify(makeProj('proj-3', 'Create an HR Policy Update', proj3qs), null, 2));
fs.writeFileSync(path.join(outProjs, 'proj-4.json'), JSON.stringify(makeProj('proj-4', 'Run a Hiring Loop for One Role', proj4qs), null, 2));
fs.writeFileSync(path.join(outProjs, 'proj-5.json'), JSON.stringify(makeProj('proj-5', 'Prepare a Monthly HR Ops Report', proj5qs), null, 2));

console.log("Successfully generated realistic, unique, 10-question data files.");
